import Layout from '../components/layout'
import '@/styles/globals.css'
import Head from "next/head";
import Navbar from '@/navbar_components/navbar';
export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Component {...pageProps} />
      </main>
    </>
  )
}